---
- name: List VPC Compute images
  hosts: localhost
  vars:
    ibmcloud_api_key: "{{ lookup('env', 'IC_API_KEY') }}"
    region: "{{ lookup('env', 'IC_REGION') }}"
  collections:
   - ibm.cloudcollection

  tasks:
    - name: "Pull available compute images for {{ region }} region "
      ibm_is_images_info:
      register: images_list
    - name: Set images as fact
      set_fact:
        cacheable: True
        available: "{{ images_list.resource.images }}"
      
    # - name: "List name and ID of available images {{ region }} region"
    #   debug:
    #     var: images_list.resource.images |
    #          items2dict(key_name='name', value_name='id')

    - name: "List full details"
      debug:
        msg: "{{ available | json_query(\"[?status==`available`].name\") }}"


    # - name: Display things
    #   debug:
    #     var: item
    #   loop: "{{ images_list.resource.images | json_query('[][?status==`available`]) }}"
    
    # - name: Display Filtered Result - One expression - one liner
    #   debug:
    #     msg: "{{ images_list.resource.images | json_query(\"[]\") }}"
