---
- name: Create IBM Cloud VPC and Set Environment Facts 
  hosts: localhost
  vars_files: 
    - ../vars.yml
  collections:
   - ibm.cloudcollection
  tasks:
    - name: Save Region as fact
      set_fact:
        cacheable: True
        region: "{{ region }}"

    - name: "Gather zones in {{ region }} region "
      ibm_is_zones_info:
        region_: "{{ region }}"
      register: regional_zones

    - name: Save Zones as fact
      set_fact:
        cacheable: True
        zones: "{{ regional_zones.resource.zones }}"

    - name: Gather Resource Group ID
      ibm_resource_group_info:
        name: "{{ resource_group }}"
      register: rg

    - name: Save Resource Group as fact
      set_fact:
        cacheable: True
        resourcegroup: "{{ rg.resource['id'] }}"

    - name: "Create VPC in {{ region }} region"
      ibm_is_vpc:
        name: "{{ name_prefix }}-vpc"
        state: available
        resource_group: "{{ resourcegroup }}"
        tags: 
          - "owner:ryantiffany"
          - "deployedwith:ansible"
      register: vpc_create_output

    - name: Save VPC as fact
      set_fact:
        cacheable: True
        vpc: "{{ vpc_create_output.resource }}"

    - name: Retrieve image for compute instances 
      ibm_is_image_info:
        name: "{{ instance_image }}"
      register: instanceimage

    - name: Save OS Image as fact
      set_fact:
        cacheable: True
        image: "{{ instanceimage.resource }}"


    - name: "Gather {{ region }} SSH key to use for VSI"
      ibm_is_ssh_key_info: 
        name: "{{ ssh_key }}"
        resource_group: "{{ resourcegroup }}"
      register: sshkey
