---
- name: Create Flowlogs collector
  hosts: localhost
  vars_files: 
    - ../vars.yml
  collections:
   - ibm.cloudcollection

  tasks:
    - name: Gather COS Instance ID
      ibm_resource_instance_info:
        name: "{{ cos_instance }}"
        location: "global"
        resource_group_id: "{{ resourcegroup }}"
        service: "cloud-object-storage"
      register: cos_flowlogs_instance

    - name: Create COS bucket for VPC Flowlogs
      ibm_cos_bucket:
        bucket_name: "{{ name_prefix }}-{{ region }}-vpc-flowlog-collector-bucket-of-doom"
        region_location: "{{ region }}"
        storage_class: "standard"
        resource_instance_id: "{{ cos_flowlogs_instance.resource['id'] }}"
        id: "{{ bucket.id | default(omit) }}"
      register: flowlogs_bucket

    - name: Save Flowlogs bucket as fact
      set_fact:
        cacheable: True
        bucket: "{{ flowlogs_bucket.resource }}"

    - name: "Configure flowlogs for VPC"
      ibm_is_flow_log: 
        name: "{{ name_prefix }}-vpc-flowlog-collector"
        storage_bucket: "{{ flowlogs_bucket.resource['bucket_name'] }}" 
        target:  "{{ vpc.id }}"
        active: True
        resource_group: "{{ resourcegroup }}"
        id: "{{ flowlog_collector.id | default(omit) }}"
      register: vpc_flowlog_collector

    - name: Set collector as fact for cleanup scripts 
      set_fact:
        cacheable: True
        flowlog_collector: "{{ vpc_flowlog_collector.resource }}"